### ISSUE TITLE
BigQuery prerequisites 

### ISSUE THREAD

**Issue by sergey-tihon** [mastoj/BigQueryProvider#1]
@mastoj What should be installed on `Win`/`macOS` to run/use BigQuery TP?

On my machine TP cannot execute this line https://github.com/mastoj/BigQueryProvider/blob/WIP/src/BigQueryProvider/BigQueryHelper.fs#L6

**Comment by mastoj** [comment]
@sergey-tihon you need to install the google cloud sdk: https://cloud.google.com/sdk/downloads#versioned

It should work on windows as well, but I haven't used it on Windows. If it is a problem I can change the branch to return a hard coded string.

**Comment by mastoj** [comment]
@sergey-tihon I hard coded an example result from the call to `bq` so you shouldn't need the google cloud sdk any more. It's in the WIP branch.

**Comment by mastoj** [comment]
btw. the pre requisites will change later on. This was the fastest way to get the schema from the queries. It is not 100 % clear how to get schema from the http api, but it should be possible since the bq tool is using the http api as well.
